before_script:
  - source ~/.bashrc
  - mkdir -p cache

cache:
  paths:
    - cache

stages:
  - build
  - test
  - HLS
  - gateSynthesis

# Note: we cannot use submodule commit as cache key, so we do it manually in
# subfolder of a big cache
cbuild:
  stage: build
  artifacts:
    paths:
      - build/bin
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make all

benchBuild:
  stage: build
  artifacts:
    paths:
      - build_bench
  script:
    - cd tests
    - make all
    - mkdir ../build_bench
    - mv ./*/*.riscv32_hw ../build_bench/

catapult_ASIC:
  stage: HLS
  artifacts:
    paths:
      - comet.vhdl
      - script.dc
      - script.dc.sdc
    expire_in: 200y
  script:
    - mkdir build-catapult-asic
    - cd build-catapult-asic
    - catapult -shell -file $CI_PROJECT_DIR/scripts/catapult_asic.tcl
    - mv Catapult/doCore.v1/concat_rtl.vhdl ../comet.vhdl
    - mv Catapult/doCore.v1/concat_rtl.vhdl.dc ../script.dc
    - mv Catapult/doCore.v1/concat_rtl.vhdl.dc.sdc ../script.dc.sdc

designCompiler:
  stage: gateSynthesis
  artifacts:
    paths:
      - comet-gate.vhdl
      - comet-gate.v
    expire_in: 200y
  dependencies:
    - catapult_ASIC
  script:
    - mkdir build-dc
    - cp comet.vhdl ./build-dc/concat_rtl.vhdl
    - cp script.dc ./build-dc/concat_rtl.vhdl.dc
    - cp script.dc.sdc ./build-dc/concat_rtl.vhdl.dc.sdc
    - cd build-dc
    - echo "write -hierarchy -format verilog -output gate.v" >> concat_rtl.vhdl.dc
    - echo "write -hierarchy -format vhdl -output gate.vhdl" >> concat_rtl.vhdl.dc
    - design_vision -f concat_rtl.vhdl.dc -no_gui
    - mv gate.vhdl ../comet-gate.vhdl
    - mv gate.v ../comet-gate.v


catapult_Xilinx:
  stage: HLS
  artifacts:
    paths:
      - comet.vhdl
      - comet.v
    expire_in: 200y
  script:
    - mkdir build-catapult-xilinx
    - cd build-catapult-xilinx
    - catapult -shell -file $CI_PROJECT_DIR/scripts/catapult_xilinx.tcl
    - mv Catapult/doCore.v1/concat_rtl.vhdl ../comet.vhdl
    - mv Catapult/doCore.v1/concat_rtl.v ../comet.v


test:atomic:
  stage: test
  script:
    - cd build/bin
    - ./atomicTests $CI_PROJECT_DIR/tests/atomicTests

test:applications:
  stage: test
  script:
    - cd tests/basic_tests
    - ./runTests.sh
